export AWS_EC2_INSTANCE_ECDSA_SSH_KEY_PATH=$HOME/.ssh/id_ecdsa.pub
export AWS_EC2_KEYPAIR_PATH=$HOME/.ssh/alma.pem
export AWS_EC2_INSTANCE_PUBLIC_IP="34.254.248.136"
export AWS_EC2_INSTANCE_DEFAULT_USER=ec2-user